config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :room_messages do 
    get "destroy_all"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_messages, dependent: :destroy
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :user
  belongs_to :room

  def as_json(options)
    super(options).merge(user_avatar_url: user.url_image).merge(user_id: user.id).merge(update_time: self.updated_at.strftime("%d/%m/%Y at %I:%M"))
  end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :room
  has_many   :room_messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @room = Room.first

    @room_messages = @room.room_messages.includes(:user)
    @room_message = RoomMessage.new room: @room
  end
end

app/controllers/room_message_controller.rb
class RoomMessageController < ApplicationController
end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
  before_action :load_entities, only: [:create]

  def create
		@user = User.find(params[:user_id])
    @room_message = RoomMessage.create user: @user,
                                       room: @room,
                                       message: params.dig(:room_message, :message)
		RoomChannel.broadcast_to @room, @room_message
  end

	def destroy_all
		room_messages = RoomMessage.all
		if room_messages.delete_all
			redirect_to root_url
		end
	end

  protected

  def load_entities
    @room = Room.find params.dig(:room_message, :room_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_chat_channel.haml
:javascript
	$(function() {

		$("[data-channel-subscribe-#{user.id}='room']").each(function(index, element) {
			var $element = $(element),
					room_id = $element.data('room-id')
			$element.animate({ scrollTop: $element.prop("scrollHeight")}, 1000)        
			
			App.cable.subscriptions.create(
				{
					channel: "RoomChannel",
					room: room_id
				},
				{
					received: function(data) {
						current_id = "#{user.id}"
						messageTemplate = $("[data-role='message-template-" + current_id + "']");
						var content = messageTemplate.children().clone(true, true);
						
						if (parseInt(current_id) == data.user_id) {
							bg_box = "sender-person message-content w-100"
							dynamic_col = "col-4"
						} else {
							bg_box = "receiver-person message-content w-100"
							dynamic_col = "col-8"
						}

						content.find("[data-role='message-box']").attr("class", bg_box);
						content.find("[data-role='user-avatar']").attr({'src': data.user_avatar_url, 'class': 'avatar', 'height': '50px', 'width': '50px'});
						content.find("[data-role='message-text']").text(data.message);
						content.find("[data-role='message-date']").text(data.update_time);
						content.find("[data-role='dynamic-coloumn']").attr("class", dynamic_col);

						$element.append(content);
						$element.animate({ scrollTop: $element.prop("scrollHeight")}, 1000);
					}
				}
			);
		});
	});

app/views/home/index.html.haml
%nav.navbar.navbar-dark.bg-dark
	%a.navbar-brand{:href => "#"}
		%img.d-inline-block.align-top{:alt => "", :height => "30", :src => "https://simpul.tech/logo-transparent.png", :width => "30"}/
		Challange Interview from SIMPUL TECH ( Hanafi Desar) 

.container
	.my-4
		.row 
			- @users.each do | user|
				.col-lg-6.col-12.my-4.text-center
					.card
						.card-body
							.row 
								.col-2
									= image_tag(user.url_image, class: "w-20", height: "80px")
								.col-10.text-left
									%h2= user.name
									%smalll= user.description

							%hr
							.chat{"data-channel-subscribe-#{user.id}"=> "room", "data-room-id"=>"#{Room.first.id}"}
								- @room_messages.each do |room_message|
									- if room_message.present?
										.row
											- if room_message.user&.id == user&.id
												.col-4
											.chat-box{class: "col-8"}
												.chat-message-container 
													.d-flex
														=image_tag(room_message.user&.url_image || "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_640.png", class: "avatar", height: "50px", width: "50px")
														.message-content.w-100{class: "#{room_message.user&.id == user&.id ? 'sender-person' : 'receiver-person'}"}
															%p.mb-1.text-left
																=room_message.message
															.text-right
																%small
																	=room_message.created_at.strftime("%d/%m/%Y at %I:%M")
								.d-none{"data-role" => "message-template-#{user.id}"}
									.row
										.col-4{"data-role" => "dynamic-coloumn"}
										%div{class: "col-8"}
											.chat-message-container 
												.d-flex
													%img.avatar{:alt => "", "data-role" => "user-avatar", :src => ""}/
													.message-content{"data-role" => "message-box"}
														%p.mb-1.text-left{"data-role" => "message-text"}
														.text-right
															%small{"data-role" => "message-date"}
							= simple_form_for @room_message, url: room_messages_path(@room_message, :user_id => user.id), remote: true do |form|
								.input-group.mb-3.mt-3
									.col-10 		
										= form.input :message, as: :string, label: false, input_html: { class: "form-control " }
									.col-2
										= form.submit "Send", class: 'btn btn-primary chat-input w-100'
								= form.input :room_id, as: :hidden

				= render partial: 'chat_channel', :locals => {:user => user}

		.row.mt-2
			.col.text-right
				=link_to destroy_all_room_messages_path, class: "btn btn-danger" do
					="Delete All Chat"

		
		

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Simpul
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = yield